apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "service.serviceAccountName" . }}
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.service.healthCheckPath }}
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 100
          readinessProbe:
            httpGet:
              path: {{ .Values.service.healthCheckPath }}
              port: http
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 100
          env:
            - name: spring_profiles_active
              value: {{ .Values.springProfile }}
            - name: KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: JAVA_OPTS
              value: -XX:MaxRAMPercentage=80.0
            - name: TZ
              value: Europe/Berlin
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
